[project]
name = "rldl-clg"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[classic-control]>=1.2.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "tensorflow>=2.20.0",
    "torch>=2.8.0",
]
